name: Push
on:
  push:
    branches:
      - main

jobs:
  update-dist-and-release:
    name: Update dist files and release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      - run: yarn install

      - run: yarn build

      - uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          file_pattern: dist/**
          add_options: -u --force
          commit_message: 'chore(dist): Update dist [automated commit]'
          commit_user_name: cobraz
          commit_user_email: cobraz@users.noreply.github.com
